[package]
name = "sqlite_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = { version = "0.4" }
core = { path = "../../crates/core" }

